In [7]:
import numpy as np

arr = np.arange(1,26)

arr = arr.reshape((5,5))

print("Matrix:")
print(arr)

print("\nFirst Row:")
print(arr[0])

print("\nLast Column:")
print(arr[:,4])

print("\nDiagonal Elements:")
print(arr[0,0])
print(arr[1,1])
print(arr[2,2])
print(arr[3,3])
print(arr[4,4])


Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row:
[1 2 3 4 5]

Last Column:
[ 5 10 15 20 25]

Diagonal Elements:
1
7
13
19
25


In [18]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Matrix A:")
print(a)

print("\nMatrix B:")
print(b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a @ b)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


3. Create a NumPy array of numbers from 1 to 100 and print all numbers
divisible by 3 using Boolean indexing.


In [19]:
import numpy as np

arr = np.arange(1,101)

print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


4. Create a 4 × 4 matrix and replace all even numbers with 0

In [20]:
import numpy as np

arr = np.arange(1,17)

arr = arr.reshape((4,4))

print("Original Matrix:")
print(arr)

arr[arr % 2 == 0] = 0

print("\nModified Matrix:")
print(arr)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Matrix:
[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


5. Create a 5 × 5 matrix of random integers and find:
○ Maximum value
○ Minimum value
○ Mean
○ Median


In [21]:
import numpy as np

arr = np.random.randint(1,100,(5,5))

print("Matrix:")
print(arr)

print("\nMaximum Value:")
print(arr.max())

print("\nMinimum Value:")
print(arr.min())

print("\nMean:")
print(arr.mean())

print("\nMedian:")
print(np.median(arr))

Matrix:
[[77 92 32 41 38]
 [85 47 74 86 41]
 [55 58 22 58 45]
 [43 14 17 73 92]
 [32 95 27 35 88]]

Maximum Value:
95

Minimum Value:
14

Mean:
54.68

Median:
47.0


6. Create a NumPy array containing 20 random numbers and sort it in
ascending and descending order

In [22]:
import numpy as np

arr = np.random.randint(1,100,20)

print("Original Array:")
print(arr)

print("\nAscending Order:")
print(np.sort(arr))

print("\nDescending Order:")
print(np.sort(arr)[::-1])

Original Array:
[75 60 71 88  9 26 93 41 95 77 55 17 10 66  9 61 47 57 69 76]

Ascending Order:
[ 9  9 10 17 26 41 47 55 57 60 61 66 69 71 75 76 77 88 93 95]

Descending Order:
[95 93 88 77 76 75 71 69 66 61 60 57 55 47 41 26 17 10  9  9]


7. Create a 6 × 6 matrix and print:
○ Main diagonal
○ Upper triangular part
○ Lower triangular part

In [23]:
import numpy as np

arr = np.arange(1,37)

arr = arr.reshape((6,6))

print("Matrix:")
print(arr)

print("\nMain Diagonal:")
print(arr.diagonal())

print("\nUpper Triangular Part:")
print(np.triu(arr))

print("\nLower Triangular Part:")
print(np.tril(arr))

Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Main Diagonal:
[ 1  8 15 22 29 36]

Upper Triangular Part:
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]

Lower Triangular Part:
[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


8. Create a NumPy array of 20 elements and reshape it into:
○ 4 × 5 matrix
○ 2 × 10 matrix
○ 5 × 4 matrix


In [26]:
arr = np.arange(1,21)

print("Original Array:")
print(arr)

print("\n4 x 5 Matrix:")
print(arr.reshape(4,5))

print("\n2 x 10 Matrix:")
print(arr.reshape(2,10))

print("\n5 x 4 Matrix:")
print(arr.reshape(5,4))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4 x 5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

2 x 10 Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

5 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


9. Create a 5 × 5 matrix and calculate the sum of: 
○ Each row 
○ Each column 

In [25]:
arr = np.arange(1,26)

arr = arr.reshape((5,5))

print("Matrix:")
print(arr)

print("\nSum of Each Row:")
print(arr.sum(axis=1))

print("\nSum of Each Column:")
print(arr.sum(axis=0))

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sum of Each Row:
[ 15  40  65  90 115]

Sum of Each Column:
[55 60 65 70 75]


10. Create two arrays and find all common elements between them. 

In [29]:
arr1 = np.array([1, 2, 3, 4, 5, 6])

arr2 = np.array([4, 5, 6, 7, 8, 9])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nCommon Elements:")
print(np.intersect1d(arr1, arr2))

Array 1:
[1 2 3 4 5 6]

Array 2:
[4 5 6 7 8 9]

Common Elements:
[4 5 6]


11. Create a 5 × 5 matrix and find the position (row and column index) 
of the largest element. 

In [30]:
arr = np.random.randint(1,100,(5,5))

print("Matrix:")
print(arr)

max_pos = np.unravel_index(arr.argmax(), arr.shape)

print("\nLargest Element:")
print(arr.max())

print("\nPosition (Row, Column):")
print(max_pos)

Matrix:
[[29 13  9  1 13]
 [44 30 39  6 99]
 [77 76 58 78 96]
 [40 15 53 27 89]
 [43 47 54 97 86]]

Largest Element:
99

Position (Row, Column):
(np.int64(1), np.int64(4))


12. Create a dataset of students' marks using a NumPy array and find: 
● Highest marks 
● Lowest marks 
● Average marks 
● Students scoring above average 

In [31]:
marks = np.array([78, 85, 92, 67, 88, 74, 95, 81, 69, 90])

print("Students Marks:")
print(marks)

print("\nHighest Marks:")
print(marks.max())

print("\nLowest Marks:")
print(marks.min())

average = marks.mean()

print("\nAverage Marks:")
print(average)

print("\nStudents Scoring Above Average:")
print(marks[marks > average])

Students Marks:
[78 85 92 67 88 74 95 81 69 90]

Highest Marks:
95

Lowest Marks:
67

Average Marks:
81.9

Students Scoring Above Average:
[85 92 88 95 90]
